#!/usr/bin/env bash
set -euo pipefail
BASE=/opt/awg31-panel
cd "$BASE"
chmod +x install-balancer.sh install-local-balancer-node.sh install-balancer-node.sh 2>/dev/null || true
./install-balancer.sh
# Install the node agent locally using the token generated by the panel installer.
./install-local-balancer-node.sh
systemctl --no-pager --full status nova-awg-balancer-node.service || true
echo
printf '%s\n' 'Cluster base installation complete.' 'Now open /balancer and add additional VPS nodes.'
